#!/usr/bin/env python3
"""Type-II chamber, divisibility, and isotropic-ray gate for Delta_5.

This verifier checks target-side BKM lattice arithmetic:

* type-II simple reflections are generated by the three delta_i;
* the distinct type-II Coxeter pairs have no finite braid relation;
* type-I chamber automorphisms permute the three type-II walls and fix rho;
* type-I square-two roots have ambient divisibility one and are absent from
  the Delta_5 Humbert divisor packet;
* type-II square-two roots have ambient divisibility two and order one in the
  Delta_5 Humbert divisor packet;
* the primitive isotropic boundary rays a_ij=delta_i+delta_j are isotropic;
* their signed multiplicity is 10 and decomposes as 1+9;
* the Gritsenko--Nikulin isotropic directions u_{ij,r} give nine directions
  on each primitive isotropic ray.

It does not construct compact source representatives, Pfaffian orientations,
O2 wall atlases, mirror discriminants, protected traces, or a parity
decomposition of the target BKM root spaces.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from collections import Counter
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path


COMPUTE_DIR = Path(__file__).resolve().parent
if str(COMPUTE_DIR) not in sys.path:
    sys.path.insert(0, str(COMPUTE_DIR))

from verify_square_root import phi_01_coefficients


MANIFEST_NAME = "manifest.json"
README_NAME = "README.md"
SUCCESS_STATUS = "TYPE_II_CHAMBER_ISOTROPIC_VERIFIED"
EXPECTED_KIND = "type_ii_chamber_isotropic_lattice"
DEFAULT_FIXTURE = Path("certificates/lattice/type_ii_chamber_isotropic")
DEFAULT_HUMBERT_FIXTURE = Path("certificates/automorphic/delta5_humbert_divisor")
DEFAULT_MAASS_FIXTURE = Path("certificates/automorphic/delta5_maass_character")

AMBIENT_GRAM = (
    (Fraction(0), Fraction(0), Fraction(-1)),
    (Fraction(0), Fraction(2), Fraction(0)),
    (Fraction(-1), Fraction(0), Fraction(0)),
)
ROOTS = {
    "delta_1": (Fraction(2), Fraction(-1), Fraction(0)),
    "delta_2": (Fraction(0), Fraction(-1), Fraction(2)),
    "delta_3": (Fraction(0), Fraction(1), Fraction(0)),
    "eta_12": (Fraction(-1), Fraction(0), Fraction(1)),
    "eta_13": (Fraction(1), Fraction(-1), Fraction(0)),
    "eta_23": (Fraction(0), Fraction(-1), Fraction(1)),
}
TYPE_II_ROOTS = ("delta_1", "delta_2", "delta_3")
TYPE_I_ROOTS = ("eta_12", "eta_13", "eta_23")
RHO = (Fraction(1), Fraction(-1, 2), Fraction(1))
TYPE_II_GENERATORS = {
    "s_delta1": "delta_1",
    "s_delta2": "delta_2",
    "s_delta3": "delta_3",
}
MAASS_GENERATOR_IDS = {
    "s_delta1": "typeII_delta1",
    "s_delta2": "typeII_delta2",
    "s_delta3": "typeII_delta3",
}
CHAMBER_AUTOMORPHISMS = {
    "sigma_12": ("eta_12", {"delta_1": "delta_2", "delta_2": "delta_1", "delta_3": "delta_3"}, "12"),
    "sigma_13": ("eta_13", {"delta_1": "delta_3", "delta_2": "delta_2", "delta_3": "delta_1"}, "13"),
    "sigma_23": ("eta_23", {"delta_1": "delta_1", "delta_2": "delta_3", "delta_3": "delta_2"}, "23"),
}
ISOTROPIC_RAYS = {
    "a_12": ("delta_1", "delta_2", (1, 1, 0), (1, 2, 1)),
    "a_13": ("delta_1", "delta_3", (1, 0, 1), (1, 0, 0)),
    "a_23": ("delta_2", "delta_3", (0, 1, 1), (0, 0, 1)),
}
REQUIRED_RELATIONS = frozenset(
    {
        "type_ii_generator_set",
        "type_ii_no_finite_braid",
        "aut_pii_s3_transpositions",
        "rho_s3_fixed",
        "type_i_absent_from_delta5_divisor",
        "isotropic_ray_count",
        "isotropic_multiplicity_decomposition",
        "gn_isotropic_direction_count",
        "tau_on_primitive_isotropic_rays",
    }
)
REQUIRED_FIREWALL_ROWS = frozenset(
    {
        "compact_source",
        "pfaffian_orientation",
        "o2_wall_atlas",
        "mirror_discriminant",
        "protected_trace",
        "parity_decomposition",
    }
)
FORBIDDEN_TOKENS = frozenset(
    {
        "mock",
        "placeholder",
        "todo",
        "unsupplied",
    }
)


@dataclass(frozen=True)
class TableSpec:
    path: str
    columns: tuple[str, ...]


TABLE_SPECS: tuple[TableSpec, ...] = (
    TableSpec(
        "root_divisibility.csv",
        (
            "root_id",
            "root_kind",
            "f2",
            "f3",
            "fm2",
            "square",
            "ambient_divisibility",
            "primitive_ambient",
            "divisor_support",
            "delta5_order",
            "source_reference",
            "check_status",
            "notes",
        ),
    ),
    TableSpec(
        "type_ii_generators.csv",
        (
            "generator_id",
            "root_id",
            "root_square",
            "ambient_divisibility",
            "determinant",
            "maass_value",
            "coxeter_generator",
            "source_reference",
            "check_status",
            "notes",
        ),
    ),
    TableSpec(
        "chamber_automorphisms.csv",
        (
            "automorphism_id",
            "root_id",
            "root_square",
            "ambient_divisibility",
            "delta1_image",
            "delta2_image",
            "delta3_image",
            "permutation",
            "rho_fixed",
            "source_reference",
            "check_status",
            "notes",
        ),
    ),
    TableSpec(
        "type_ii_coxeter_pairs.csv",
        (
            "pair_id",
            "left_generator",
            "right_generator",
            "root_pairing",
            "coxeter_order",
            "finite_braid",
            "source_reference",
            "check_status",
            "notes",
        ),
    ),
    TableSpec(
        "isotropic_rays.csv",
        (
            "ray_id",
            "left_root",
            "right_root",
            "f2",
            "f3",
            "fm2",
            "delta1_coeff",
            "delta2_coeff",
            "delta3_coeff",
            "square",
            "primitive_in_type_ii_lattice",
            "root_lattice_divisibility",
            "pair_delta1",
            "pair_delta2",
            "pair_delta3",
            "chamber_member",
            "s3_orbit",
            "source_reference",
            "check_status",
            "notes",
        ),
    ),
    TableSpec(
        "isotropic_multiplicities.csv",
        (
            "ray_id",
            "n",
            "l",
            "m",
            "phi_index_n",
            "phi_l",
            "coefficient",
            "affine_a1_contribution",
            "gn_tau",
            "coefficient_decomposition",
            "source_reference",
            "check_status",
            "notes",
        ),
    ),
    TableSpec(
        "gn_isotropic_directions.csv",
        (
            "direction_id",
            "ray_id",
            "direction_index",
            "ray_generator_coeff",
            "square",
            "gn_tau_total",
            "direction_count_for_ray",
            "source_reference",
            "check_status",
            "notes",
        ),
    ),
    TableSpec(
        "chamber_relations.csv",
        (
            "relation_id",
            "relation_kind",
            "computed_value",
            "expected_value",
            "defect_rank",
            "source_reference",
            "check_status",
            "notes",
        ),
    ),
    TableSpec(
        "scalar_firewall.csv",
        (
            "firewall_id",
            "forbidden_substitute",
            "excluded",
            "defect_rank",
            "source_reference",
            "check_status",
            "notes",
        ),
    ),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fixture", type=Path, default=DEFAULT_FIXTURE)
    parser.add_argument("--humbert-fixture", type=Path, default=DEFAULT_HUMBERT_FIXTURE)
    parser.add_argument("--maass-fixture", type=Path, default=DEFAULT_MAASS_FIXTURE)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def read_manifest(fixture: Path) -> dict:
    manifest_path = fixture / MANIFEST_NAME
    readme_path = fixture / README_NAME
    if not manifest_path.exists():
        raise ValueError(f"missing manifest: {manifest_path}")
    if not readme_path.exists() or not readme_path.read_text(encoding="utf-8").strip():
        raise ValueError(f"missing nonempty README: {readme_path}")
    return json.loads(manifest_path.read_text(encoding="utf-8"))


def read_table(fixture: Path, spec: TableSpec) -> list[dict[str, str]]:
    path = fixture / spec.path
    if not path.exists():
        raise ValueError(f"missing table: {path}")
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        if tuple(reader.fieldnames or ()) != spec.columns:
            raise ValueError(
                f"{spec.path}: expected columns {spec.columns}, got {tuple(reader.fieldnames or ())}"
            )
        rows = list(reader)
    if not rows:
        raise ValueError(f"{spec.path}: expected at least one row")
    for row in rows:
        if None in row:
            raise ValueError(f"{spec.path}: unparsed CSV fields in row {row}")
    return rows


def read_humbert_support(humbert_fixture: Path) -> dict[str, int]:
    path = humbert_fixture / "support_components.csv"
    if not path.exists():
        raise ValueError(f"missing Humbert support table: {path}")
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)
    support: dict[str, int] = {}
    for row in rows:
        if row.get("support_member") == "true":
            support[row["wall_label"]] = int(row["delta5_order"])
    return support


def read_maass_values(maass_fixture: Path) -> dict[str, tuple[int, int]]:
    path = maass_fixture / "character_values.csv"
    if not path.exists():
        raise ValueError(f"missing Maass character table: {path}")
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)
    values: dict[str, tuple[int, int]] = {}
    for row in rows:
        generator_id = row["generator_id"]
        values[generator_id] = (int(row["character_value"]), int(row["determinant_value"]))
    return values


def int_cell(row: dict[str, str], key: str) -> int:
    try:
        return int(row[key])
    except ValueError as exc:
        raise ValueError(f"{key} is not an integer in row {row}") from exc


def bool_cell(row: dict[str, str], key: str) -> bool:
    value = row[key].strip().lower()
    if value == "true":
        return True
    if value == "false":
        return False
    raise ValueError(f"{key} is not a boolean in row {row}")


def check_row(row: dict[str, str], table_name: str) -> None:
    if row.get("check_status") != "verified":
        raise ValueError(f"{table_name}: row is not verified: {row}")
    if not row.get("source_reference", "").strip():
        raise ValueError(f"{table_name}: missing source_reference: {row}")
    haystack = " ".join(row.values()).lower()
    for token in FORBIDDEN_TOKENS:
        if token in haystack:
            raise ValueError(f"{table_name}: forbidden token {token!r} in {row}")


def require_equal(actual: object, expected: object, label: str) -> None:
    if actual != expected:
        raise ValueError(f"{label}: expected {expected!r}, got {actual!r}")


def pair(left: tuple[Fraction, Fraction, Fraction], right: tuple[Fraction, Fraction, Fraction]) -> Fraction:
    return sum(
        left[i] * AMBIENT_GRAM[i][j] * right[j]
        for i in range(3)
        for j in range(3)
    )


def add_vectors(*vectors: tuple[Fraction, Fraction, Fraction]) -> tuple[Fraction, Fraction, Fraction]:
    return tuple(sum(vector[i] for vector in vectors) for i in range(3))


def scale_vector(coefficient: Fraction, vector: tuple[Fraction, Fraction, Fraction]) -> tuple[Fraction, Fraction, Fraction]:
    return tuple(coefficient * entry for entry in vector)


def reflect(vector: tuple[Fraction, Fraction, Fraction], root: tuple[Fraction, Fraction, Fraction]) -> tuple[Fraction, Fraction, Fraction]:
    norm = pair(root, root)
    if norm == 0:
        raise ValueError(f"cannot reflect in isotropic vector {root}")
    factor = Fraction(2) * pair(vector, root) / norm
    return add_vectors(vector, scale_vector(-factor, root))


def root_by_vector(vector: tuple[Fraction, Fraction, Fraction]) -> str:
    for root_id in TYPE_II_ROOTS:
        if ROOTS[root_id] == vector:
            return root_id
    raise ValueError(f"vector is not a type-II simple root: {vector}")


def root_lattice_vector(coeffs: tuple[int, int, int]) -> tuple[Fraction, Fraction, Fraction]:
    vectors = [scale_vector(Fraction(coeffs[i]), ROOTS[TYPE_II_ROOTS[i]]) for i in range(3)]
    return add_vectors(*vectors)


def ambient_divisibility(vector: tuple[Fraction, Fraction, Fraction]) -> int:
    if not all(entry.denominator == 1 for entry in vector):
        raise ValueError(f"non-integral vector: {vector}")
    a, b, c = (int(entry) for entry in vector)
    values = [abs(c), abs(2 * b), abs(a)]
    return math.gcd(math.gcd(values[0], values[1]), values[2])


def primitive_ambient(vector: tuple[Fraction, Fraction, Fraction]) -> bool:
    if not all(entry.denominator == 1 for entry in vector):
        return False
    values = [abs(int(entry)) for entry in vector]
    return math.gcd(math.gcd(values[0], values[1]), values[2]) == 1


def primitive_coeffs(coeffs: tuple[int, int, int]) -> bool:
    values = [abs(value) for value in coeffs]
    return math.gcd(math.gcd(values[0], values[1]), values[2]) == 1


def root_lattice_divisibility(vector: tuple[Fraction, Fraction, Fraction]) -> int:
    values = [abs(int(pair(vector, ROOTS[root_id]))) for root_id in TYPE_II_ROOTS]
    return math.gcd(math.gcd(values[0], values[1]), values[2])


def coxeter_order(left: str, right: str) -> int:
    pairing = pair(ROOTS[left], ROOTS[right])
    if left == right:
        return 1
    if pairing == 0:
        return 2
    if pairing == -1:
        return 3
    if pairing == -2:
        return 0
    raise ValueError(f"unhandled Coxeter pairing {pairing} for {left},{right}")


def coefficient(n: int, l: int) -> int:
    value = phi_01_coefficients().get((n, l), Fraction(0))
    if value.denominator != 1:
        raise ValueError(f"nonintegral phi_01 coefficient f({n},{l})={value}")
    return int(value)


def verify_manifest(manifest: dict) -> None:
    require_equal(manifest.get("lattice_kind"), EXPECTED_KIND, "manifest lattice_kind")
    require_equal(manifest.get("certified"), True, "manifest certified")
    require_equal(manifest.get("chamber_isotropic_certified"), True, "manifest chamber_isotropic_certified")
    require_equal(manifest.get("compact_source"), False, "manifest compact_source")
    require_equal(manifest.get("pfaffian_orientation"), False, "manifest pfaffian_orientation")
    require_equal(manifest.get("o2_wall_atlas"), False, "manifest o2_wall_atlas")
    require_equal(manifest.get("mirror_discriminant"), False, "manifest mirror_discriminant")
    require_equal(manifest.get("protected_trace"), False, "manifest protected_trace")
    require_equal(manifest.get("parity_decomposition"), False, "manifest parity_decomposition")
    require_equal(manifest.get("tables"), [spec.path for spec in TABLE_SPECS], "manifest tables")


def verify_root_divisibility(rows: list[dict[str, str]], support: dict[str, int]) -> dict[str, bool]:
    seen: set[str] = set()
    type_i_absent: dict[str, bool] = {}
    for row in rows:
        check_row(row, "root_divisibility.csv")
        root_id = row["root_id"]
        if root_id in seen:
            raise ValueError(f"root_divisibility.csv: duplicate root_id {root_id}")
        seen.add(root_id)
        if root_id not in ROOTS:
            raise ValueError(f"root_divisibility.csv: unexpected root_id {root_id}")
        root = ROOTS[root_id]
        displayed = (Fraction(int_cell(row, "f2")), Fraction(int_cell(row, "f3")), Fraction(int_cell(row, "fm2")))
        require_equal(displayed, root, f"{root_id} coordinates")
        expected_kind = "type_II" if root_id in TYPE_II_ROOTS else "type_I"
        require_equal(row["root_kind"], expected_kind, f"{root_id} root_kind")
        require_equal(int(pair(root, root)), int_cell(row, "square"), f"{root_id} square")
        require_equal(ambient_divisibility(root), int_cell(row, "ambient_divisibility"), f"{root_id} divisibility")
        require_equal(primitive_ambient(root), bool_cell(row, "primitive_ambient"), f"{root_id} primitive")
        support_member = root_id in support
        require_equal(bool_cell(row, "divisor_support"), support_member, f"{root_id} divisor_support")
        require_equal(int_cell(row, "delta5_order"), support.get(root_id, 0), f"{root_id} delta5_order")
        if expected_kind == "type_I":
            type_i_absent[root_id] = not support_member and int_cell(row, "delta5_order") == 0
    require_equal(seen, set(ROOTS), "root divisibility coverage")
    return type_i_absent


def verify_type_ii_generators(rows: list[dict[str, str]], maass_values: dict[str, tuple[int, int]]) -> None:
    seen: set[str] = set()
    for row in rows:
        check_row(row, "type_ii_generators.csv")
        generator_id = row["generator_id"]
        if generator_id in seen:
            raise ValueError(f"type_ii_generators.csv: duplicate generator_id {generator_id}")
        seen.add(generator_id)
        if generator_id not in TYPE_II_GENERATORS:
            raise ValueError(f"type_ii_generators.csv: unexpected generator_id {generator_id}")
        root_id = TYPE_II_GENERATORS[generator_id]
        root = ROOTS[root_id]
        require_equal(row["root_id"], root_id, f"{generator_id} root_id")
        require_equal(int(pair(root, root)), int_cell(row, "root_square"), f"{generator_id} root_square")
        require_equal(ambient_divisibility(root), int_cell(row, "ambient_divisibility"), f"{generator_id} divisibility")
        require_equal(int_cell(row, "determinant"), -1, f"{generator_id} determinant")
        require_equal(int_cell(row, "maass_value"), -1, f"{generator_id} maass_value")
        maass_generator_id = MAASS_GENERATOR_IDS[generator_id]
        if maass_generator_id not in maass_values:
            raise ValueError(f"type_ii_generators.csv: missing Maass generator {maass_generator_id}")
        maass_value, determinant_value = maass_values[maass_generator_id]
        require_equal(int_cell(row, "maass_value"), maass_value, f"{generator_id} Maass packet value")
        require_equal(int_cell(row, "determinant"), determinant_value, f"{generator_id} Maass packet determinant")
        require_equal(bool_cell(row, "coxeter_generator"), True, f"{generator_id} coxeter_generator")
    require_equal(seen, set(TYPE_II_GENERATORS), "type-II generator coverage")


def verify_chamber_automorphisms(rows: list[dict[str, str]]) -> dict[str, bool]:
    seen: set[str] = set()
    rho_fixed: dict[str, bool] = {}
    for row in rows:
        check_row(row, "chamber_automorphisms.csv")
        automorphism_id = row["automorphism_id"]
        if automorphism_id in seen:
            raise ValueError(f"chamber_automorphisms.csv: duplicate automorphism_id {automorphism_id}")
        seen.add(automorphism_id)
        if automorphism_id not in CHAMBER_AUTOMORPHISMS:
            raise ValueError(f"chamber_automorphisms.csv: unexpected automorphism_id {automorphism_id}")
        root_id, image_map, permutation = CHAMBER_AUTOMORPHISMS[automorphism_id]
        root = ROOTS[root_id]
        require_equal(row["root_id"], root_id, f"{automorphism_id} root_id")
        require_equal(int(pair(root, root)), int_cell(row, "root_square"), f"{automorphism_id} root_square")
        require_equal(ambient_divisibility(root), int_cell(row, "ambient_divisibility"), f"{automorphism_id} divisibility")
        computed_images = {
            root_id_inner: root_by_vector(reflect(ROOTS[root_id_inner], root))
            for root_id_inner in TYPE_II_ROOTS
        }
        require_equal(computed_images, image_map, f"{automorphism_id} image map")
        require_equal(row["delta1_image"], image_map["delta_1"], f"{automorphism_id} delta1_image")
        require_equal(row["delta2_image"], image_map["delta_2"], f"{automorphism_id} delta2_image")
        require_equal(row["delta3_image"], image_map["delta_3"], f"{automorphism_id} delta3_image")
        require_equal(row["permutation"], permutation, f"{automorphism_id} permutation")
        fixed = reflect(RHO, root) == RHO
        require_equal(bool_cell(row, "rho_fixed"), fixed, f"{automorphism_id} rho_fixed")
        rho_fixed[automorphism_id] = fixed
    require_equal(seen, set(CHAMBER_AUTOMORPHISMS), "chamber automorphism coverage")
    return rho_fixed


def verify_type_ii_coxeter_pairs(rows: list[dict[str, str]]) -> dict[str, int]:
    expected_pairs = {
        ("s_delta1", "s_delta2"),
        ("s_delta1", "s_delta3"),
        ("s_delta2", "s_delta3"),
    }
    seen: set[tuple[str, str]] = set()
    finite_count = 0
    for row in rows:
        check_row(row, "type_ii_coxeter_pairs.csv")
        left = row["left_generator"]
        right = row["right_generator"]
        key = (left, right)
        if key in seen:
            raise ValueError(f"type_ii_coxeter_pairs.csv: duplicate pair {key}")
        seen.add(key)
        if key not in expected_pairs:
            raise ValueError(f"type_ii_coxeter_pairs.csv: unexpected pair {key}")
        left_root = TYPE_II_GENERATORS[left]
        right_root = TYPE_II_GENERATORS[right]
        root_pairing = int(pair(ROOTS[left_root], ROOTS[right_root]))
        order = coxeter_order(left_root, right_root)
        finite = order != 0
        require_equal(int_cell(row, "root_pairing"), root_pairing, f"{row['pair_id']} root_pairing")
        require_equal(int_cell(row, "coxeter_order"), order, f"{row['pair_id']} coxeter_order")
        require_equal(bool_cell(row, "finite_braid"), finite, f"{row['pair_id']} finite_braid")
        finite_count += 1 if finite else 0
    require_equal(seen, expected_pairs, "type-II Coxeter pair coverage")
    return {"finite_count": finite_count, "pair_count": len(seen)}


def verify_isotropic_rays(rows: list[dict[str, str]]) -> dict[str, int]:
    seen: set[str] = set()
    ray_square: dict[str, int] = {}
    for row in rows:
        check_row(row, "isotropic_rays.csv")
        ray_id = row["ray_id"]
        if ray_id in seen:
            raise ValueError(f"isotropic_rays.csv: duplicate ray_id {ray_id}")
        seen.add(ray_id)
        if ray_id not in ISOTROPIC_RAYS:
            raise ValueError(f"isotropic_rays.csv: unexpected ray_id {ray_id}")
        left_root, right_root, coeffs, _triple = ISOTROPIC_RAYS[ray_id]
        require_equal(row["left_root"], left_root, f"{ray_id} left_root")
        require_equal(row["right_root"], right_root, f"{ray_id} right_root")
        vector = root_lattice_vector(coeffs)
        require_equal((int_cell(row, "f2"), int_cell(row, "f3"), int_cell(row, "fm2")), tuple(int(entry) for entry in vector), f"{ray_id} coordinates")
        require_equal((int_cell(row, "delta1_coeff"), int_cell(row, "delta2_coeff"), int_cell(row, "delta3_coeff")), coeffs, f"{ray_id} coeffs")
        square = int(pair(vector, vector))
        require_equal(square, int_cell(row, "square"), f"{ray_id} square")
        require_equal(bool_cell(row, "primitive_in_type_ii_lattice"), primitive_coeffs(coeffs), f"{ray_id} primitive")
        require_equal(int_cell(row, "root_lattice_divisibility"), root_lattice_divisibility(vector), f"{ray_id} root_lattice_divisibility")
        pairings = tuple(int(pair(vector, ROOTS[root_id])) for root_id in TYPE_II_ROOTS)
        require_equal((int_cell(row, "pair_delta1"), int_cell(row, "pair_delta2"), int_cell(row, "pair_delta3")), pairings, f"{ray_id} pairings")
        require_equal(bool_cell(row, "chamber_member"), all(value <= 0 for value in pairings), f"{ray_id} chamber_member")
        require_equal(row["s3_orbit"], "isotropic_boundary_three_orbit", f"{ray_id} s3_orbit")
        ray_square[ray_id] = square
    require_equal(seen, set(ISOTROPIC_RAYS), "isotropic ray coverage")
    return ray_square


def verify_isotropic_multiplicities(rows: list[dict[str, str]]) -> dict[str, int]:
    seen: set[str] = set()
    tau_values: dict[str, int] = {}
    for row in rows:
        check_row(row, "isotropic_multiplicities.csv")
        ray_id = row["ray_id"]
        if ray_id in seen:
            raise ValueError(f"isotropic_multiplicities.csv: duplicate ray_id {ray_id}")
        seen.add(ray_id)
        if ray_id not in ISOTROPIC_RAYS:
            raise ValueError(f"isotropic_multiplicities.csv: unexpected ray_id {ray_id}")
        _left_root, _right_root, _coeffs, triple = ISOTROPIC_RAYS[ray_id]
        n, l, m = triple
        require_equal((int_cell(row, "n"), int_cell(row, "l"), int_cell(row, "m")), triple, f"{ray_id} triple")
        require_equal(int_cell(row, "phi_index_n"), n * m, f"{ray_id} phi_index_n")
        require_equal(int_cell(row, "phi_l"), l, f"{ray_id} phi_l")
        coeff = coefficient(n * m, l)
        require_equal(int_cell(row, "coefficient"), coeff, f"{ray_id} coefficient")
        affine = int_cell(row, "affine_a1_contribution")
        tau = int_cell(row, "gn_tau")
        require_equal(affine, 1, f"{ray_id} affine_a1_contribution")
        require_equal(tau, 9, f"{ray_id} gn_tau")
        require_equal(coeff, affine + tau, f"{ray_id} coefficient decomposition")
        require_equal(row["coefficient_decomposition"], "10=1+9", f"{ray_id} coefficient_decomposition")
        tau_values[ray_id] = tau
    require_equal(seen, set(ISOTROPIC_RAYS), "isotropic multiplicity coverage")
    return tau_values


def verify_gn_isotropic_directions(rows: list[dict[str, str]], ray_square: dict[str, int], tau_values: dict[str, int]) -> dict[str, int]:
    seen: set[str] = set()
    counts: Counter[str] = Counter()
    indices: dict[str, set[int]] = {ray_id: set() for ray_id in ISOTROPIC_RAYS}
    for row in rows:
        check_row(row, "gn_isotropic_directions.csv")
        direction_id = row["direction_id"]
        if direction_id in seen:
            raise ValueError(f"gn_isotropic_directions.csv: duplicate direction_id {direction_id}")
        seen.add(direction_id)
        ray_id = row["ray_id"]
        if ray_id not in ISOTROPIC_RAYS:
            raise ValueError(f"gn_isotropic_directions.csv: unexpected ray_id {ray_id}")
        index = int_cell(row, "direction_index")
        if index < 1 or index > 9:
            raise ValueError(f"gn_isotropic_directions.csv: direction index outside 1..9 in {row}")
        expected_direction_id = f"u_{ray_id[2:]}_{index}"
        require_equal(direction_id, expected_direction_id, f"{direction_id} direction_id")
        require_equal(int_cell(row, "ray_generator_coeff"), 1, f"{direction_id} ray_generator_coeff")
        require_equal(int_cell(row, "square"), ray_square[ray_id], f"{direction_id} square")
        require_equal(int_cell(row, "gn_tau_total"), tau_values[ray_id], f"{direction_id} gn_tau_total")
        require_equal(int_cell(row, "direction_count_for_ray"), 9, f"{direction_id} direction_count_for_ray")
        counts[ray_id] += 1
        indices[ray_id].add(index)
    require_equal(set(counts), set(ISOTROPIC_RAYS), "GN direction ray coverage")
    for ray_id in ISOTROPIC_RAYS:
        require_equal(counts[ray_id], 9, f"{ray_id} direction count")
        require_equal(indices[ray_id], set(range(1, 10)), f"{ray_id} direction indices")
    return dict(counts)


def verify_chamber_relations(
    rows: list[dict[str, str]],
    type_i_absent: dict[str, bool],
    rho_fixed: dict[str, bool],
    coxeter_data: dict[str, int],
    ray_square: dict[str, int],
    tau_values: dict[str, int],
    direction_counts: dict[str, int],
) -> None:
    relation_values = {
        "type_ii_generator_set": len(TYPE_II_GENERATORS),
        "type_ii_no_finite_braid": 1 if coxeter_data["finite_count"] == 0 and coxeter_data["pair_count"] == 3 else 0,
        "aut_pii_s3_transpositions": len(CHAMBER_AUTOMORPHISMS),
        "rho_s3_fixed": 1 if all(rho_fixed.values()) else 0,
        "type_i_absent_from_delta5_divisor": 1 if all(type_i_absent.values()) else 0,
        "isotropic_ray_count": len(ray_square),
        "isotropic_multiplicity_decomposition": 1 if all(tau == 9 for tau in tau_values.values()) else 0,
        "gn_isotropic_direction_count": sum(direction_counts.values()),
        "tau_on_primitive_isotropic_rays": 9 if all(tau == 9 for tau in tau_values.values()) else 0,
    }
    seen: set[str] = set()
    for row in rows:
        check_row(row, "chamber_relations.csv")
        relation_id = row["relation_id"]
        if relation_id in seen:
            raise ValueError(f"chamber_relations.csv: duplicate relation_id {relation_id}")
        seen.add(relation_id)
        if relation_id not in REQUIRED_RELATIONS:
            raise ValueError(f"chamber_relations.csv: unexpected relation_id {relation_id}")
        require_equal(int_cell(row, "computed_value"), relation_values[relation_id], f"{relation_id} computed_value")
        require_equal(int_cell(row, "computed_value"), int_cell(row, "expected_value"), f"{relation_id} expected_value")
        require_equal(int_cell(row, "defect_rank"), 0, f"{relation_id} defect_rank")
    require_equal(seen, REQUIRED_RELATIONS, "chamber relation coverage")


def verify_firewall(rows: list[dict[str, str]]) -> None:
    seen: set[str] = set()
    for row in rows:
        check_row(row, "scalar_firewall.csv")
        substitute = row["forbidden_substitute"]
        if substitute in seen:
            raise ValueError(f"scalar_firewall.csv: duplicate substitute {substitute}")
        seen.add(substitute)
        require_equal(bool_cell(row, "excluded"), True, f"{substitute} excluded")
        require_equal(int_cell(row, "defect_rank"), 0, f"{substitute} defect_rank")
    missing = REQUIRED_FIREWALL_ROWS - seen
    if missing:
        raise ValueError(f"scalar_firewall.csv missing rows: {sorted(missing)}")


def main() -> int:
    args = parse_args()
    try:
        manifest = read_manifest(args.fixture)
        verify_manifest(manifest)
        support = read_humbert_support(args.humbert_fixture)
        maass_values = read_maass_values(args.maass_fixture)
        tables = {spec.path: read_table(args.fixture, spec) for spec in TABLE_SPECS}
        type_i_absent = verify_root_divisibility(tables["root_divisibility.csv"], support)
        verify_type_ii_generators(tables["type_ii_generators.csv"], maass_values)
        rho_fixed = verify_chamber_automorphisms(tables["chamber_automorphisms.csv"])
        coxeter_data = verify_type_ii_coxeter_pairs(tables["type_ii_coxeter_pairs.csv"])
        ray_square = verify_isotropic_rays(tables["isotropic_rays.csv"])
        tau_values = verify_isotropic_multiplicities(tables["isotropic_multiplicities.csv"])
        direction_counts = verify_gn_isotropic_directions(
            tables["gn_isotropic_directions.csv"], ray_square, tau_values
        )
        verify_chamber_relations(
            tables["chamber_relations.csv"],
            type_i_absent,
            rho_fixed,
            coxeter_data,
            ray_square,
            tau_values,
            direction_counts,
        )
        verify_firewall(tables["scalar_firewall.csv"])
    except Exception as exc:  # noqa: BLE001 - command-line verifier
        print(f"TYPE_II_CHAMBER_ISOTROPIC_FAILED: {exc}", file=sys.stderr)
        return 1
    print(SUCCESS_STATUS)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
